# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{radiant-users-extension}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Dirk Kelly"]
  s.date = %q{2011-01-05}
  s.description = %q{Makes Radiant better by adding users!}
  s.email = ["dk@dirkkelly.com"]
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.homepage = %q{http://github.com/dirkkelly/radiant-users-extension}
  s.post_install_message = %q{
    Add this to your radiant project with:
      config.gem 'radiant-users-extension', :version => '1.0.0'
    }
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Users for Radiant CMS}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<radiant>, ["~> 0.9.2"])
      s.add_runtime_dependency(%q<devise>, ["~> 1.1.5"])
    else
      s.add_dependency(%q<radiant>, ["~> 0.9.2"])
      s.add_dependency(%q<devise>, ["~> 1.1.5"])
    end
  else
    s.add_dependency(%q<radiant>, ["~> 0.9.2"])
    s.add_dependency(%q<devise>, ["~> 1.1.5"])
  end
end

