# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{radiant-users-extension}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Christopher Rankin", "Dirk Kelly"]
  s.date = %q{2010-11-23}
  s.description = %q{Users creates support for non-admin users with API access}
  s.email = %q{dk@squaretalent.com}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "README.md",
    "Rakefile",
    "VERSION",
    "config/routes.rb",
    "cucumber.yml",
    "db/migrate/20100311014641_add_api_key_to_users.rb",
    "db/migrate/20100311021835_add_access_to_user.rb",
    "features/support/env.rb",
    "features/support/paths.rb",
    "lib/radiant-users-extension.rb",
    "lib/tasks/users_extension_tasks.rake",
    "lib/users/lib/login_system.rb",
    "lib/users/models/user.rb",
    "lib/users/models/user/scoped.rb",
    "radiant-users-extension.gemspec",
    "spec/datasets/scoped_users_dataset.rb",
    "spec/models/user_spec.rb",
    "spec/models/visitor_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb",
    "users_extension.rb"
  ]
  s.homepage = %q{http://github.com/dirkkelly/radiant-users-extension}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Users Extension for Radiant CMS}
  s.test_files = [
    "spec/datasets/scoped_users_dataset.rb",
    "spec/models/user_spec.rb",
    "spec/models/visitor_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

