# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{radiant-scoped-extension}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Christopher Rankin", "Dirk Kelly"]
  s.date = %q{2010-09-27}
  s.description = %q{Scoped allows you to create non-admin users with API access}
  s.email = %q{dk@squaretalent.com}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "README.md",
     "Rakefile",
     "VERSION",
     "config/routes.rb",
     "cucumber.yml",
     "db/migrate/20100311014641_add_api_key_to_users.rb",
     "db/migrate/20100311021835_add_access_to_user.rb",
     "features/support/env.rb",
     "features/support/paths.rb",
     "lib/scoped/lib/login_system.rb",
     "lib/scoped/models/user.rb",
     "lib/scoped/models/user/scoped.rb",
     "lib/tasks/scoped_extension_tasks.rake",
     "radiant-scoped-extension.gemspec",
     "scoped_extension.rb",
     "spec/datasets/scoped_dataset.rb",
     "spec/models/user_spec.rb",
     "spec/models/visitor_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/squaretalent/radiant-scoped-extension}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Scoped Extension for Radiant CMS}
  s.test_files = [
    "spec/datasets/scoped_dataset.rb",
     "spec/models/user_spec.rb",
     "spec/models/visitor_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

